[build]
  buildCommand = "pnpm install --frozen-lockfile && npx prisma generate && pnpm build && npx prisma migrate deploy"

[deploy]
  startCommand = "node build/server.js"
  healthcheckPath = "/ping_"
