name: Running CI/CD
on:
  push:
    branches:
      - homolog

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Install pnpm 📦
        run: npm install -g pnpm@9.15.2

      - name: version pnpm 📦
        run: pnpm -v

      - name: Create pnpm cache directory
        run: mkdir -p ~/.pnpm-store

      - name: Cache dependencies 💎
        id: cache-pnpm
        uses: actions/cache@v4
        env:
          cache-name: cache-pnpm
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: List the state of node modules
        if: ${{ steps.cache-pnpm.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: pnpm  list

      - name: Install dependencies 📦
        run: pnpm install

      - name: Run Lint 💎
        run: pnpm run lint

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy files to S3
        run: |
          ${{ secrets.S3_FILES }}

      - name: Run Tests 🧪
        run: |
          npx prisma generate
          pnpm run test

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{secrets.ECR_REPOSITORY}} -f docker/homolog/Dockerfile.homolog .
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
